import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import LayoutHome from "../components/LayoutHome/LayoutHome";
import Hero from "../components/Hero/Hero";
import Benefits from "../components/Benefits/Benefits";
import SuccessSection from "../components/SuccessSection/SuccessSection";
import Reviews from "../components/Reviews/Reviews";
import ProjectsTiles from "../components/ProjectSections/ProjectsTiles";
import QuestionsSection from "../components/QuestionsSection/QuestionsSection";
import VideoSection from "../components/VideoSection/VideoSection";
import CardServices from "../components/CardServices/CardServices";


export default function Home() {
  const [ready, setReady] = useState(false);
  const router = useRouter();
  
  


  useEffect(() => {
    if (router.isReady) {
      setReady(true);
    }
  }, [router.isReady]);





  return (
    ready && (
    <>
      <Head>
        <title>Web-agency</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutHome>
        <Hero/>
        <Benefits/>
        <SuccessSection/>
        <VideoSection/>
        <Reviews/>
        {/* <Services/> */}
        <CardServices/>
        <ProjectsTiles title="Projects"/>
        <QuestionsSection/>
       
        
      </LayoutHome>
    
    </>
    )
  );
}
